# Generated by Django 5.2.3 on 2025-06-20 10:31

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[authentication.models.validate_agronix_email]),
        ),
    ]
